### ISSUE TITLE
Merge (root pointer move)

### ISSUE THREAD

**Issue by parkan** [mediachain/L-SPACE#16]
This should be quick, rewrite `describedBy` from `Canonical` to new `Blob`. May need #13 to be done properly (i.e. can repoint only if you signed the canonical)

Roughly:

- [ ] blindly move edge
- [ ] copy subtree
- [ ] mark old edge as deprecated (tree is still reachable but we don't ref the old object in future writes)
- [ ] check permissions

**Comment by parkan** [comment]
Thought: does this constitute an "edit"/leave a trail in some way? It's possible to represent merges in an otherwise immutable system like IPFS by moving the root IPNS pointer, which maps quite elegantly to this operation, but I wonder if we should do this non-destructively too.

**Comment by parkan** [comment]
Other, possibly wacky idea: what if merges are first-class objects??

**Comment by parkan** [comment]
### Priority:
* oldest canonical wins
* newest/oldest HEAD wins
* largest tree wins
* arbitrary?

**Comment by parkan** [comment]
### Mechanism:
* deprecate B's `described_by`, create `described_by₁` pointing at A's `described_by.outV`, copy tree
* add `A --- superceded_by --> B`, copy tree
* just copy the damn tree (?!?)

**Comment by parkan** [comment]
### Tree copy
This is the tricky part because of how it interacts with HEAD revision building (#20):
* take `B.outE('describedBy').outV...` and connected subtree and just paste it at tip of A -- simple and append-only but _does not preserve chronological ordering_ so resolving overriding values requires sorting the path, but maybe this is OK
* rearrange both trees to interleave in write order, update all `describedBy`, throw old trees away
* flatten B tree + A HEAD, attach

**Comment by bigs** [comment]
# General Approach

- pseudo signature: `mergeCanonicals : Canonical -> Canonical -> Canonical`
  - first canonical, A, is the one that will be integrated into the second canonical, B
- connect `A -> B` via `superceded-by` edge
- mark A's `described-by` as deprecated
- connect A's root node to B via `described-by`

**Comment by yusefnapora** [comment]
Here's a fancy drawing of what we've got in mind: https://docs.google.com/drawings/d/1B8_RrfNrhMAZNuwHtuGtJpc2SDUJhete2YU5J2TEzi0/edit?usp=sharing

**Comment by bigs** [comment]
@parkan this initial impl is done. it's very simple & doesn't concern itself w/ semantics for merged authors at the moment

**Comment by parkan** [comment]
sweet! do we have tests?

**Comment by bigs** [comment]
@parkan yep!
