### ISSUE TITLE
[low priority] better Ook

### ISSUE THREAD

**Issue by parkan** [mediachain/L-SPACE#25]
The monkey emoji does Ook a disservice, would be great to have a proper orangutan

**Comment by parkan** [comment]
I have to say I'm rather fond of this Ook from https://www.instagram.com/misterhope/

![2q](https://cloud.githubusercontent.com/assets/204986/14183978/e7200f9c-f740-11e5-8ab6-be4dda48c2e6.png)

**Comment by bigs** [comment]
:+1:

**Comment by yusefnapora** [comment]
yeah, agreed :smile: 
:shipit:

**Comment by parkan** [comment]
Might write to the artist and ask if it's cool to use for an OSS project?

**Comment by parkan** [comment]
Ack just realized that I ended up trimming out some of the signature, that wasn't intentional! overeager magic wand tool :disappointed:

**Comment by parkan** [comment]
Original: https://www.instagram.com/p/1unBNRlaBP/?taken-by=misterhope

**Comment by denisnazarov** [comment]
http://misterhope.com/contact/

Will hit him up later.

**Comment by parkan** [comment]
this is lovely but probably a low priority given that this is no longer our focus repo
