### ISSUE TITLE
Modular signing hash and crypto algorithms

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/L-SPACE#27]
The current WIP signing implementation uses [the pgp wrapper used by the sbt-pgp plugin](https://github.com/sbt/sbt-pgp/tree/master/gpg-library/src), which has some unfortunate limits:

- doesn't let you specify the digest algorithm; hardcoded to SHA-1
- only has RSA, DSA, and ElGamal crypto algorithms to choose from
- doesn't understand X.509 / openssl certificates, so keys need to be stored in PGP "keyrings"

And fundamentally PGP is a message-oriented protocol that isn't a perfect fit for our domain.  But it was quick to get up and running with thanks to the wrapper.

I'd like to implement our own wrapper around [bouncy castle](https://www.bouncycastle.org/) or possibly the native Java crypto API that is similar to the pgp-wrapper but more modular.  Or, if that seems to daunting, fork the PGP lib to expose more internals and allow different algorithms.

**Comment by bigs** [comment]
@yusefnapora this could be relevant https://github.com/abstractj/kalium

**Comment by yusefnapora** [comment]
hmm, interesting... I'll check it out

**Comment by parkan** [comment]
libsodium++
