### ISSUE TITLE
OrientDB schema: constraints, migrations, indexes

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/L-SPACE#5]
So far we haven't been using any orientdb specific features, but we'll need to dig in and define some schema constraints and indexes soon for consistency and performance.

There's two main pages in the orient docs about schemas: [orient graph schema docs](http://orientdb.com/docs/last/Tutorial-Using-schema-with-graphs.html) and the more general [document schema docs](http://orientdb.com/docs/last/Schema.html).  These both apply, since the graph api is a layer on top of the document api.  So you can use any of the constraints in the document schema api (min/max value, mandatory, read-only, etc) when defining properties for an edge or vertex class.

The graph schema api lets you constrain edge classes so they can only point `in` or `out` to certain vertex classes, which seems useful.   For example, the `defined-by` edge could be constrained to only go from `Canonical` to `MetadataBlob` (which would be the parent class of the specific blob types).  You can also create a uniqueness constraint on `(in, out)` to prevent multiple edges of the same class between the same vertices.

[Indexes](http://orientdb.com/docs/last/Indexes.html) are another area where we need to hit the orient api directly, and they would also benefit from a migration strategy. 

We should consider using the [orient-migrations](https://github.com/springnz/orientdb-migrations) project to keep track of and apply migrations.  There's also some code in there for managing orient session pools, which could be useful when we set up a live server.

One thing to note is that class names are based on label names, with either `E_` or `V_` prepended (for edge and vertex classes).  The `orientdb-migrations` code will automatically prepend those, but otherwise we need to remember to do it ourselves.

**Comment by parkan** [comment]
We should note the [schema related work](https://github.com/mediachain/L-SPACE/commits/master/l_space/src/main/scala/io/mediachain/util/orient/MigrationHelper.scala) here.

I believe edge cardinality restrictions fall under schema, as well.

**Comment by parkan** [comment]
Deprioritized now that L-SPACE is more of a *consumer*/read cache than write cache
