### ISSUE TITLE
Implement API Methods (backend)

### ISSUE THREAD

**Issue by bigs** [mediachain/L-SPACE#54]
- [x] Fetch all canonical's (of works, paginated)
- [x] Get rev history for a work by canonical ID ("subtree")
- [ ] Submit a revision (by MetadataBlob ID)
- [ ] Ingest metadata with one of our dispatchers

**Comment by parkan** [comment]
@bigs tried asking this in the doc comments: is the write an upsert or distinct update/insert? Also, is this intentionally missing "ingest"?

**Comment by bigs** [comment]
@parkan ah no ingest should be there. adding. regarding upsert... i see it as being "insert" and "modify"

**Comment by bigs** [comment]
as in, two fns

**Comment by parkan** [comment]
what happens on duplicate insert then? i.e. if I add something but we decide it's a dupe
