### ISSUE TITLE
Implement CLI

### ISSUE THREAD

**Issue by bigs** [mediachain/L-SPACE#55]

**Comment by denisnazarov** [comment]
From the CLI google doc by @bigs :

- Given a (house-written) schema translator and a file/some files, a private key, and an “identity” (just a name for now), ingest a dataset into Mediachain
```
$ mediachain ingest tate ~/tate/artworks cole.crt +cole
Successfully ingested 1000 objects.
```

- Query for a list of Canonical IDs in the system (paginated)
```
$ mediachain list --page 1
Page 1 of Canonical IDs:
ffffffffffffffffffffffffff
eeeeeeeeeeeeeeeeeeeeeeeeee
...
```

- Given a Canonical ID, return the entire revision tree (as JSON--formatting unknown)
```
$ mediachain get ffffffffffffffffffffffffff
{
  …
}
```

- Given a blob ID, submit a revision of a piece of Metadata
```
$ mediachain revise ffffffffffffffffffffffffff updated.json
Updated ffffffffffffffffffffffffff.
```

- Given a Canonical ID representing a Person, find all works they authored
```
$ mediachain works dddddddddddddddddddddddddd
Fetching works for John Smith:
ffffffffffffffffffffffffff
Eeeeeeeeeeeeeeeeeeeeeeeeee
```

- Configure the path to the Mediachain server (dumped into ./.mediachain)
```
$ mediachain config 127.0.0.1:1337
```

**Comment by parkan** [comment]
Needs concrete output specs
