### ISSUE TITLE
TranslatorDispatcher fails if you don't provide signing identity

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/L-SPACE#62]
Right now if you only provide the first two arguments to TranslatorDispatcher.dispatch(), it will fail with an signature error.  But if you provide an invalid or missing path to your key, it will just warn that it couldn't load the key and will import without signing anything.

We should make the two-arg call default to ingestion without signing.

**Comment by parkan** [comment]
I think this doesn't matter right now
