### ISSUE TITLE
Remove Ingress/ingestion

### ISSUE THREAD

**Issue by parkan** [mediachain/L-SPACE#66]
Because the real insert logic will happen at mediachain level, L-SPACE does not need to run ingestions. All inserts will happen atomically through #65

**Comment by bigs** [comment]
ya tho i'm not sure we should remove it until we have an idea of what can/can't be reused

**Comment by parkan** [comment]
I think chopping it out will make the rest of the codebase much more legible, and we can always take it from a branch

**Comment by parkan** [comment]
(obvs we will reuse some logic in the client)

**Comment by parkan** [comment]
Though on second thought you are right, we haven't really thought the separation through yet in terms of duplicate detection etc flow so let's low-priority this for now
