### ISSUE TITLE
gRPC Authentication

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/L-SPACE#69]
Out of the box, gRPC supports SSL/TLS encryption for the connection, and OAuth2 for client auth.  It's also [possible](https://github.com/matthild/reproduce_tls_bug/blob/master/src/test/java/io/grpc/testing/integration/TlsTest.java) to require a client certificate for mutual SSL authentication.  That could be used to ensure that a client has a certificate signed by a "Level-1" Peer as [spec'd in the RFC](https://github.com/mediachain/mediachain/blob/master/rfc/mediachain-rfc-2.md#node-keys-and-certificates).

That seems like a decent plan, since we have certificate management written into the design already.  OAuth seems much more compatible with systems that have a central authority, which is something we'd obviously like to avoid.

So, the basic idea is (mostly just re-stating the RFC):

- Transactors have certificates signed by a "Level-0" signing key, the public component of which is baked into all mediachain peer and client software.  This produces a "Level-1" certificate.

- The Transactor runs two separate services; one requires a client certificate signed by a "Level-1" cert, the other just uses server-authentication to verify the identity of the Transactor.

- Clients request that a Transactor sign their self-generated certificate using the "public" (server-auth only) service.  This may require proof-of-work to discourage spammers.

- Once they've received a signed client cert, a Client can issue write requests on the client-authenticated service.

- Read-only Transactor endpoints could possibly go on the "public" service, although I kind of like the idea of having that service only be responsible for signing client certs.

**Comment by parkan** [comment]
The signing part can be completely separate from the rest (maybe we can even just use something off-the-shelf for it)

Glancing at the code sample, it seems like they're using a single ssl context for the whole service, but I think you can probably do it on an endpoint-by-endpoint basis?

**Comment by bigs** [comment]
ya we just have to find a way of cleanly decentralizing the cert registry. it can't be a ux hurdle

**Comment by yusefnapora** [comment]
Brain-dumping more thoughts on this before moving on....

I think that the TLS stuff applies to the entire channel, but it might be possible to inspect the SSL context from the endpoint handler (possibly with an interceptor?)  in which case you could check there whether the client was authenticated with a cert and accept or reject as appropriate.  But I'm not sure if you can set it up to optionally require client authentication; I think maybe if you enable it the client must provide a valid cert to obtain a connection at all.

The OAuth code is actually an extension of a generic "metadata credentials" plugin system, but the only [example](http://www.grpc.io/docs/guides/auth.html#extending-grpc-to-support-other-authentication-mechanisms) of providing your own plugin in the docs is in c++, and I can't find any analogue in the java implementation.  Might be possible to hook into it though for per-endpoint authorization...

A possible flow would be to have a single client-authenticated endpoint that returns an access token, then attach that token to the other requests... that would still require two services though.

**Comment by parkan** [comment]
![interceptor](http://vignette3.wikia.nocookie.net/starwars/images/e/e8/TIEinterceptor_bf.jpg/revision/latest?cb=20070113135746)

**Comment by parkan** [comment]
OK, based on our discussion about separate L-SPACE + writer design this does not apply here for the moment (assuming world-readable db for the moment)

Writer + transactor auth up for separate discussion.
